version: 0.0
os: linux
files:
  - source: /target/CRM.war
    destination: /opt/tomcat/webapps/
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
  BeforeInstall:
    - location: scripts/cleanup
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      
